export { default as Hero } from './Hero'
export { default as StatsBar } from './StatsBar'
export { default as UspGrid } from './UspGrid'
export { default as MachinesGrid } from './MachinesGrid'
export { default as TeamSection } from './TeamSection'
export { default as ProcessSteps } from './ProcessSteps'
export { default as SuccessStory } from './SuccessStory'
export { default as ContactForm } from './ContactForm'
export { default as Footer } from './Footer'
export { default as ContentBlock } from './ContentBlock'
export { default as Reveal } from './Reveal'
export type { SectorPageData } from './types'
